# Generated by Django 5.1.4 on 2024-12-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=2)),
                ('minutes', models.CharField(max_length=2)),
                ('seconds', models.CharField(max_length=2)),
                ('description_text', models.TextField()),
                ('image_name', models.CharField(max_length=255)),
                ('percent', models.CharField(max_length=3)),
                ('countdown', models.IntegerField()),
            ],
        ),
    ]
